version: '2'
services:
  jenkins-swarm-client:
     build: ./jenkins-swarm-client
     network_mode: "host"
     privileged: true
     restart: always
     volumes:
       - 'data:/data'
  label-gen:
     build: ./label-gen
     network_mode: "host"
     privileged: true
     restart: always
     volumes:
       - 'data:/data'
volumes:
  data:
