version: '2'
services:
  jenkins-swarm-client:
     build: ./jenkins-swarm-client
     network_mode: "host"
     privileged: true
     restart: always
  label-gen:
     build: ./label-gen
     network_mode: "host"
     privileged: true
     restart: always
