FROM balenalib/%%BALENA_MACHINE_NAME%%-openjdk:latest

# Install tools and remove layer cache afterwards
RUN apt-get -q update && apt-get install -yq --no-install-recommends \
  curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create and switch to the Jenkins user
ARG UNAME=jenkins
RUN useradd --create-home ${UNAME}
USER ${UNAME}

# Switch to working directory for our app
WORKDIR /home/jenkins

# Copy all the source code in.
COPY . .

# Download the Jenkins swarm client
RUN curl -s -o swarm-client.jar \
  https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.18/swarm-client-3.18.jar

# Launch on container startup.
CMD ["bash", "./start.sh"]
